- name: Installing ngin and start serice
  hosts: mongodb
  becomes: yes # root access
  tasks:
    - name: Install nginx
      ansible.buitin.yum:
        name: nginx
        state: installed

     - name: Start nginx
       ansible.builtin.service:
        name: nginx
        state: started   